module_settings:
  module_name: "BounceBan - Bulk Email Verification"
  module_description: "Submit emails for bulk verification and retrieve results. Supports up to 500,000 emails per task. Use polling to check status and get results when complete."