module_settings:
  module_name: "BounceBan - Delete Bulk Task"
  module_description: "Delete an existing bulk verification task and all associated results from BounceBan. This action is permanent and cannot be undone. Requires confirmation before deletion."