module_settings:
  module_name: "BounceBan - Check Domain or Email"
  module_description: "Check if an email address or domain is free, disposable, role-based, catch-all, temporary, or a spam trap. Provides detailed characteristics about the email provider and domain configuration."